"""Cola de trabajos

Tercer paso de la Fase 2. El analisis se ejecutaba dentro de la peticion
HTTP: con cinco articulos son minutos con la peticion abierta, y cualquier
proxy corta a los treinta o sesenta segundos. Estas columnas convierten
`run` y `run_item` —que ya llevaban el estado de cada articulo— en una cola
de la que puede tirar un proceso aparte.

- `run_item.estado` admite `en_proceso`: un articulo tomado y sin terminar.
  Sin ese estado, dos trabajadores cogerian el mismo, y uno caido dejaria el
  suyo como pendiente sin rastro de que ya se intento.
- `run_item.intentos` y `tomado_en` permiten reintentar lo transitorio y
  recuperar lo que quedo a medias, sin repetir sin fin.
- `run.genera_estado_arte` lo pide quien encola. El trabajador no puede
  adivinarlo, y sintetizar siempre gastaria una generacion en ejecuciones
  parciales.
- `run.error_msg` para lo que impide continuar con el lote entero, como
  agotar la cuota diaria. Los fallos de un articulo suelto siguen en
  `run_item.error_msg`.

El cambio del enum no reescribe filas: MySQL solo amplia la lista de valores
admitidos, y `pendiente` sigue significando lo mismo.

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-13

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('genera_estado_arte', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('run', sa.Column('error_msg', sa.Text(), nullable=True))
    op.add_column('run_item', sa.Column('intentos', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('run_item', sa.Column('tomado_en', mysql.DATETIME(timezone=6), nullable=True))
    op.alter_column('run_item', 'estado',
               existing_type=mysql.ENUM('pendiente', 'extraido', 'ocr', 'enriquecido', 'analizado', 'guardado', 'fallido'),
               type_=sa.Enum('pendiente', 'en_proceso', 'extraido', 'ocr', 'enriquecido', 'analizado', 'guardado', 'fallido', name='estadorunitem'),
               existing_nullable=True,
               existing_server_default=sa.text("'pendiente'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('run_item', 'estado',
               existing_type=sa.Enum('pendiente', 'en_proceso', 'extraido', 'ocr', 'enriquecido', 'analizado', 'guardado', 'fallido', name='estadorunitem'),
               type_=mysql.ENUM('pendiente', 'extraido', 'ocr', 'enriquecido', 'analizado', 'guardado', 'fallido'),
               existing_nullable=True,
               existing_server_default=sa.text("'pendiente'"))
    op.drop_column('run_item', 'tomado_en')
    op.drop_column('run_item', 'intentos')
    op.drop_column('run', 'error_msg')
    op.drop_column('run', 'genera_estado_arte')
    # ### end Alembic commands ###
